### ISSUE TITLE
用 Bootstrap 美化页面的简单方法

### ISSUE THREAD

**Issue by leilayanhui** [leilayanhui/Magic-Formula-Cn#11]
# 用 Bootstrap 美化页面的简单方法
其实是纯小白的抄袭方法

1. 进入 [Bootstrap examples](http://getbootstrap.com/getting-started/#examples) 页面
2. 找一个自己喜欢的模板，用 google chrome 打开该页面
3. 在该模板页面按 `control+shift+i` 开发者工具，你就能看到 html 的编写内容了
4. 将鼠标在代码上移动，会标示出代码相应的页面区块，找到你需要的区块，点击向下的箭头，就能看到具体的代码
5. 抄写开始~

**Comment by zhangshiyinrunwithcc** [comment]
我实验了一下，发现 不能打开html编写内容：

1. 是否打开模板不对？我想打开的模板地址 http://getbootstrap.com/examples/cover/

2. 我按住的按钮是 `control + shift + i`

@leilayanhui

**Comment by leilayanhui** [comment]
google chrome 浏览器设置——更多工具——开发者工具

我用得win10，可能快捷键不一样

**Comment by zhangshiyinrunwithcc** [comment]
恩！

用google chrome 浏览器设置——更多工具——开发者工具 可以打开了。

谢！
