### ISSUE TITLE
结业项目进展

### ISSUE THREAD

**Issue by zhangshiyinrunwithcc** [leilayanhui/Magic-Formula-Cn#12]
- 项目名称：神奇公式筛股器

- 项目仓库地址 ：[Magic Formula  Cn](https://github.com/leilayanhui/Magic-Formula-Cn)

- 项目进度：

  - 前端：已完成 [注册页面、登陆页面、说明页面](https://github.com/leilayanhui/Magic-Formula-Cn/tree/yanhui-web)

  - 后端：已完成 能够抓取 tushare 的数据代码

  - 前端：待完成 交互页面
  
  - 后端：待完成 API接口 计算神奇公式 部署公网 制作keynote
  
- 所遇困难
  - 问题1：如何用 Flask-SQLAlchemy 按行或按列批量查询数据，并生成 html table？https://github.com/AIMinder/Py103/issues/275
  - 问题2：计算神奇公式还需要资产负债表里的一些数据，即需要抓取通联的数据，但它的格式和 tushare 的不同，如何将抓取的数据倒入数据库是个难点。
  
- 所需支持：

**Comment by leilayanhui** [comment]
可以把前端的地址改成 sepatate 的分支，比如

- 项目代码：https://github.com/leilayanhui/Magic-Formula-Cn/tree/yh-web-separate
- 注册页面：https://github.com/leilayanhui/Magic-Formula-Cn/blob/yh-web-separate/app/templates/register.html
- 登陆页面：https://github.com/leilayanhui/Magic-Formula-Cn/blob/yh-web-separate/app/templates/login.html
- 说明页面：（把你制作的说明页面更新上去）https://github.com/leilayanhui/Magic-Formula-Cn/blob/yh-web-separate/app/templates/help.html

**Comment by zhangshiyinrunwithcc** [comment]
- 项目名称：神奇公式筛股器

- 项目仓库地址 ：[Magic Formula  Cn](https://github.com/leilayanhui/Magic-Formula-Cn/tree/yh-web-separate)

- 项目进度：

  - 前端：已完成[注册页面](https://github.com/leilayanhui/Magic-Formula-Cn/blob/yh-web-separate/app/templates/register.html) [登陆页面](https://github.com/leilayanhui/Magic-Formula-Cn/blob/yh-web-separate/app/templates/login.html) [说明页面](https://github.com/leilayanhui/Magic-Formula-Cn/blob/yh-web-separate/app/templates/help.html)

  - 后端：已完成 能够抓取 tushare 的数据代码

  - 前端：待完成 交互页面
  
  - 后端：待完成 API接口 计算神奇公式 部署公网 制作keynote
  
- 所遇困难
  - 问题1：如何用 Flask-SQLAlchemy 按行或按列批量查询数据，并生成 html table？https://github.com/AIMinder/Py103/issues/275
  - 问题2：计算神奇公式还需要资产负债表里的一些数据，即需要抓取通联的数据，但它的格式和 tushare 的不同，如何将抓取的数据倒入数据库是个难点。
  
- 所需支持：

**Comment by leilayanhui** [comment]
fatfox 的抓取代码 ： https://github.com/leilayanhui/Magic-Formula-Cn/tree/fatfox-db-tushare
