### ISSUE TITLE
kenote 文案和视频

### ISSUE THREAD

**Issue by leilayanhui** [leilayanhui/Magic-Formula-Cn#13]
# 文案
### v1 初版
1. 买车要试驾

2. 买房要看房

3. 买股票要…
    K 线图、成交量、pe、技术图、主力、热点新闻、行业报告、看股评、听广播……
    2000多支股票到底怎么选？

4. 巴菲特说：你要拥有一双发现好股票的眼睛。
                      花四毛钱买价值一块钱的东西。

5. 同样的成本，A 公司利润20万，B公司 7.4万，A 公司业绩更好，A 公司胜出

6. 同样的收益，C 股卖 30元，D 股卖 18 元，D 股更便宜，D 股胜出

7. 乔尔 将两者结合，创造神奇公式 （一本小书配图）

8. 投资回报率，筛选出好公司
   收益率，筛选出低价格
   好业绩 + 低价格，就是你要买的股票

9. 乔尔用该方法在美股市场上投资了17年，成绩斐然
  
10. 神奇公式筛股器，计算中国股票的排名（最好能有中国股市的历史战绩）

11. 筛股票根据最新的公司财报，排列所有深沪A股，获得综合排名

12. 公布排名前 30 的股票，供你选择

13. 登陆、注册网站的视频

14. 投资的第一原则：不要亏钱！祝君好运

15. 制作团队

一个小点一张卡片，内容尽量用动画表示。卡片顺序还要调整

# 视频
v1 地址：http://pan.baidu.com/s/1nvPobO1

**Comment by leilayanhui** [comment]
v1 版不灵，得加个隐喻。

把选股比作河道支流，获得收益比作汇入大海，是否合适？

**Comment by zhangshiyinrunwithcc** [comment]
@leilayanhui 

关于keynote,我有2点想法：

- **十分重要的是，我们这场keynote的受众是谁？** 
  - 我们的受众不是真正会投资股票关心收益率的股民，而是Py103的热心python技术的小伙伴；
  - 如果受众的关注点在技术上，那么关于投资的知识点就只需要说得浅显易懂，**少一点术语**。

- **神奇公司项目的目标是什么？**
  - 是为了开发出真正面向股民的应用吗？
  - 是为了验证产品经理对神奇公式的想法吗？
  - 还是为了完成一个得票比较高的py103结业项目？

综上2点，我认为，我们的keynote，可以采用   **浅显的科普故事+技术点大放送**的展示思路。

**Comment by zhangshiyinrunwithcc** [comment]
- 浅显科普故事
  - @leilayanhui  蕙蕙已经做得差不多，我觉得，选取几张信息量小的就行；

- 技术点大放送
  - @leilayanhui  我希望**从3月13日-3月17日，主力梳理我们项目中的技术难点**，遇到需要支持的地方，我私信蕙蕙你；

**Comment by leilayanhui** [comment]
打算用种子的隐喻来讲故事

技术部分需要胭脂王提供些信息
- 数据源是什么？怎么爬取？
- 获取后如何处理？
- 如何整理出我们需要的数据？
- 如何计算、排序？最终获得综合排名？

也可以讲讲编写时遇到的坑，如何出坑等

**Comment by leilayanhui** [comment]
路演版
        - [百度云盘](http://pan.baidu.com/s/1c1Ayk3e)
        - [腾讯视频](https://v.qq.com/x/page/l03884otlxk.html)
