### ISSUE TITLE
已部署 Heroku，免费账户有诸多限制，还有 bug

### ISSUE THREAD

**Issue by leilayanhui** [leilayanhui/Magic-Formula-Cn#14]
公网地址：http://magicformulacn.herokuapp.com/
部署在 heroku 的仓库地址：https://git.heroku.com/magicformulacn.git

### 免费账户限制

1. Scale the app

`heroku ps:scale web=1`  免费账户只能设置 web=1，不能再多了

2. addons
若要使用 Heroku 提供的数据库，需要安装 addons，但免费账户不能安装

只有绑定信用卡，才能使用更多的功能……

### bug
登陆后再点击登陆，会出现错误提示：NameError: name 'logout_user' is not defined

但之前在内网测试的时候是好的。我再出查查……

**Comment by zhangshiyinrunwithcc** [comment]
### 公网地址已测试，可用

刚刚测试了，可以注册用户，然后登陆。
http://magicformulacn.herokuapp.com/

说明界面很漂亮，赞！

暂时没有遇到NameError的错误

@leilayanhui

**Comment by leilayanhui** [comment]
bug 已解决
