### ISSUE TITLE
2017.2.20  第一次会议

### ISSUE THREAD

**Issue by leilayanhui** [leilayanhui/Magic-Formula-Cn#2]
# 2017-2-20  第一次会议
### 会议时间：
2017.2.20 20：00

### 会议工具：
[Zoom](https://zoom.us/)
到时会在微信群发布链接

#### 战略定位
这个网站是否只是荐股，是否会开发数据分析功能？

面向对象是谁？普通大众、价值投资者、专业人士？

#### 一阶功能
- 建立 web 页面
- 给出排名前30的股票
- 数据范围：
  上证A股，2016、2015年中报，或者2015、2014年年报。建议根据财报的三大报表建立原始数据库，再生成神奇公式需要的数据的数据库。即使将来做调整，数据间也不会相互影响。

#### 二阶功能
- 用户注册、登陆
- 返回100支，或所有股票
  除了神奇公式的排名还有多增加几列像 excel 一样，用户可自行排序

#### 三阶功能
- 页面美化
- 生成走势图
- 回溯功能

### 进度安排
7wd2 完成组队
8w 一阶功能
9w 二阶功能
10w 二阶功能，制作 keynote
11wd5 报名路演
12wd0~12wd3 微信路演

**Comment by leilayanhui** [comment]
# 会议记录
### 目标客群：目前还存在分歧
**小白**

他们能承受多大的回撤，10000变8000，还是10000变4000？能坚持持有多久，3-5年，还是三月五周？买车要试驾，买房要看房，买股票就什么都不要了？他们不想对买入公司有任何了解、思考和信念，只想它第二天翻倍。这是我们想要服务的对象吗？又能服务多久？

**长期持有者**

为什么要长期持有，你看好这家公司什么？一定要有足够好的理由。这个理由怎么来，肯定不是道听途说。炒股的低门槛吸引了大量散户，但一赢二平七输的格局没有改变。专业机构有的是人力、物力，个人投资者是无法抗衡的。个人投资者只有时间，运用自己的智慧，投入时间获得利润。聪明的投资者多得是，，但巴菲特、芒格只有一个。真正重要的是投资理念，我们要服务的也是有自己投资理念的人。

写得比较乱啊，但希望大家能思考下。

### 执行计划
2.21 - 3.3 完成一阶功能

现在大家的脑子里还没有网站的样子，我们先把它大概的样子弄出来。建立一个内网可用的神奇公式筛股器，能在页面显示排名30的股票，同时有两项指标和综合指标的排名。做成表格形式展现。

时间|工作重点
---|---
2.21-2.22|收集神奇公式资料，公式算法
2.23-2.25|爬取数据，建立原始数据库
2.28-3.3|计算神奇公司，生产股票列表
2.28-3.3|制作内网可用的页面

**胭脂王**：有过计算神奇公式的经验，由他制定公式的算法，及需要的数据。

**许从用**：抓取数据，建立原始数据库

**fatfox**：前段，神奇公式数据库

**周绪龙**：网页美化

**严蕙**：编程能力有限，但我愿意学习，我给你们打杂，比如调整原始数据库，写文案

**雷云鹤**：前端？

**Comment by yanzhiw** [comment]
## 神奇公式小组任务分工

一句话概括神奇公式：**打折**买**好**公司。

什么是好公司：赚钱能力强。100元的本金可以赚20元的就比100元本金只能赚10元的要强~~
这个数据用**投资回报率**来体现（简单来说就是你用多少钱可以一年赚回来多少钱） 
即：EBIT/（净有形资产+净流动资产）

什么是打折：便宜性价比高。同样一年赚20元，一个卖你200，一个卖你180,180的要比200强。
这个数据用**收益率**来体现（简单来说就是购买一家一年赚X元的公司需要即：EBIT/EV

不服跑个分，这两项进行排序，然后相加，得到一个分数，分数越低越强。

### 后端

#### 数据抓取和采集
##### 我们需要的数据
EBIT（息前税前利润）=净利润＋所得税费用＋分配股利、利润或偿付利息支付的现金
净资产回报率=EBIT/（净有形资产+净流动资产） = EBIT/(货币资金+交易性金融资产 + 固定资产净额 ）
EV = 总市值（股价 * 股数）+ 净有息负债 = 股价 * 股本数 + 短期借款 +长期借款 + 应付债券

我们需要以下数据

净利润
所得税费用
分配股利、利润或偿付利息支付的现金
货币资金
交易性金融资产
固定资产净额
股价
股本数
短期借款
长期借款
应付债券

目前暂时以2016年3季度报为为内容
并且股价和股本数以检索日-1日收盘价为单位
[抓取代码API](http://tushare.org/storing.html#csv)

#### 数据加工

通过以上数据
整理出各股票的投资回报率和收益率的值
将所有股票的投资回报率和收益率进行比较，得出排名
将两个排名相加，得出一个新数值
所有股票按数值从小到大排列

#### 用户数据库
用户注册，绑定QQ或微信
记录用户注册日推荐的股票，以及排列组合

额外功能：微信提醒换仓（注册日起3个月后调仓一次，依次类推）

### 前端

#### 注册页面
用户注册及交互页面
设定用户绑定QQ 微信等的交互

#### 交互页面
设计交互页面
用户点击了解神奇公式的历史以及相关表现情况

#### 微信端
打通微信端API，可以通过公众号关键词推送相应页面
自动生成微信页面

**Comment by zhangshiyinrunwithcc** [comment]
任务分工

张诗颖 ：  前端 + 打杂
