### ISSUE TITLE
目前原始数据获取方法

### ISSUE THREAD

**Issue by leilayanhui** [leilayanhui/Magic-Formula-Cn#22]
# 2017.3.17 更新
## 财报数据
- [x] 从东方财富通获得我们需要的原始数据，导出的是 excel 格式，由 fatfox 编写代码入库到 basiceTable

**原始数据**
   - 代码
   - 名称
   - 行业
   - 净利润（最近四个季度）
   - 所得税（最近四个季度）
   - 财务费用（最近四个季度）
   - 所有者权益
   - 无形资产
   - 商誉
   - 总股本

## 股价、 总市值
- [x] 从 tushare `ts.get_today_all()` 获得原始数据，包括前一日收盘价和总市值。由 fatfox 编写代码，只将【总市值】入库到 basiceTable

# 问题，请教练指导
总市值 = 股价 * 总股本

获得总市值的方法有两种，一直接入库总市值，二入库股价，再计算后获得总市值。

1. 不同的数据源，证券代码的数量和排序不完全匹配。tushare 股票列表里少了几只股票，导致 basiceTable 里对应股票的总市值无法更新。而且 tushare 总市值这一数据显示为 `1004224.77002`，似乎单位不是元。

2. basiceTable 是应该直接写入【总市值】，还是写入【股价】，与【总股本】相乘获得【总市值】？

# 旧方法
## 财报三表
能通过 excel 下载获得，一支股票三张表。例如万科A，有一张负债表，一张利润表，一张现金流表。我们需要从前两张表中搜索特定的数据。而且每支股票的负债表的格式还不一样。即特定某一行的数据，不同的股票不一样。

现在计划用搜索中文关键词的方法获得所需数据，再倒入数据库。不知是否能成功？

## 股价、总股本
股价需要天天获取，计划采用方法2 [沪深股票日行情](https://mall.datayes.com/datapreview/1327?lang=zh)，直接下载 csv 文件，如何入库还没想好

### 方法1： tushare
[历史行情](http://tushare.org/trading.html#id2)

```
import tushare as ts
ts.get_hist_data('600848',start='2017-03-15',end='2017-03-15')
```

只能一个个股票查。我试了下 for 循环，没成功

```
import tushare as ts

with open ('stocks_list.txt', 'r',  encoding='utf8') as f:
       for line in f:
        stocks_list = list(line.split(','))

for i in stocks_list:
     df = ts.get_hist_data(i,start='2017-03-15',end='2017-03-15')
```

### 方法2： 通联
[行情数据](http://tushare.org/datayes.html#id5)

```
st = ts.Market()
df = st.MktEqud(tradeDate='20170315', field='ticker,secShortName,preClosePrice,closePrice')
df['ticker'] = df['ticker'].map(lambda x: str(x).zfill(6))
```
[getMktEqud -- 文档](https://api.wmcloud.com/docs/pages/viewpage.action?pageId=1867813#id-行情信息-getMktEqud)

需申请免费试用，30天限制

[沪深股票日行情](https://mall.datayes.com/datapreview/1327?lang=zh)

可以在上面这个链接里直接下载 csv 文件，包括总市值，不用再用股价、股本进行计算。但是如何导入数据库？

**Comment by zhangshiyinrunwithcc** [comment]
@leilayanhui 

写得很清晰
总算理解目前数据处理的困难了
按大妈所说，先获得原始数据
数据格式调整与入库可以下一步再做

**Comment by zhangshiyinrunwithcc** [comment]
@leilayanhui 
**问题** 
如何用python搜索中文关键词的方法获得所需数据

**案例**
原始数据
10家公司的10张excel表格
表格格式为xls
分别命名为表1、表2...表10
需要
从表1抽取第1列第1行数据
从表2抽取第1列第2行数据
...
从表10抽取第1列第10行数据
这群数据的特征是，数据名字为“利润”

**方案**
设定特征
搜索
爬取数据


这是我对【财务报表】困难的理解，对吗？

**Comment by zhangshiyinrunwithcc** [comment]
**问题**
xls数据如何入库？

**情境**
已有xls数据
如何入库？

**方案**
xls转为csv
csv导入sqlite

**Comment by leilayanhui** [comment]
1家公司3个 xls 文件，10家公司30个 xls 文件。这些表就是原始数据，已下载。格式为 excel。

要从A 公司的第 1 个 xls 文件中抽取特定几项数据，如行：支付利息行，列： 2016-03-31，2016-09-30 等。行是不固定，只能通过搜索关键词定位，列还算能固定，从第2列到第5列

再从A 公司的第 2 个 xls 文件中抽取特定几项数据。然后合并。

3000 多家公司都这么来一遍

现在要想办法怎么把 excel 表里的数据，导入到数据库里。而且只保留我们需要，删掉多余的数据。

那个 xls - csv - sqlite 是我刚找的，不一定对，而且这方法太麻烦了。3000多之股票，* 2 表，就是 7000 个 xls 文件……

**Comment by gzMichael** [comment]
@leilayanhui 试试这样获取全部列表：
```
import tushare as ts
df = ts.get_stock_basics()
for i in df.index:
    df2 = ts.get_k_data(i, start=dt1_str, end=dtstr)
```

**Comment by gzMichael** [comment]
@zhangshiyinrunwithcc 
> 问题
> xls数据如何入库？

```
import tushare as ts
import sqlite3
df = ts.get_stock_basics()
conn = sqlite3.connect('../mydb.sqlite')
for i in df.index:
    df2 = ts.get_k_data(i, start=dt1_str, end=dtstr)
    df2.to_sql('table_xxx',conn,if_exists='replace')
```
是要这样全部入库吗？

**Comment by leilayanhui** [comment]
谢谢 @gzMichael ，我们现在能将xls导入数据库了，暂时能做出最粗略的样子了
