### ISSUE TITLE
东方财富从哪里下载【所得税】数据？

### ISSUE THREAD

**Issue by zhangshiyinrunwithcc** [leilayanhui/Magic-Formula-Cn#23]
@leilayanhui 
**已下载**
已下载`净利润`
![4](https://cloud.githubusercontent.com/assets/19412465/24036390/4a9668fc-0b34-11e7-98a7-7ebad54c1ad6.png)

**缺失**
缺少`所得税`数据
![3](https://cloud.githubusercontent.com/assets/19412465/24036334/0d542a38-0b34-11e7-9105-44468597aea5.png)

**问题**
东方财富从哪里下载`所得税`数据？

**Comment by leilayanhui** [comment]
在软件菜单里面找【高级选股】—— 左上【待选指标】—— 财务报表 —— 一般企业 —— 利润表 里就有了

**Comment by zhangshiyinrunwithcc** [comment]
@leilayanhui 

谢谢！已找到。
