### ISSUE TITLE
新的神奇公式是怎样运算的？

### ISSUE THREAD

**Issue by zhangshiyinrunwithcc** [leilayanhui/Magic-Formula-Cn#26]
**旧的神奇公式**

```
EBIT（息前税前利润）=净利润＋所得税费用＋分配股利、利润或偿付利息支付的现金
净资产回报率=EBIT/（净有形资产+净流动资产） = EBIT/(货币资金+交易性金融资产 + 固定资产净额 ）
EV = 总市值（股价 * 股数）+ 净有息负债 = 股价 * 股本数 + 短期借款 +长期借款 + 应付债券
```
**目前采用的数据**

我看到目前采用的数据是@蕙蕙从东方财富上下载的excel数据。

```
净利润
所得税
财务费用
所有者权益
无形资产
商誉
股价
股本
```
**新的神奇公式**

```
现在有的数据，比如商誉、财务费用，并不在原先设计的神奇公式
（EV = 总市值（股价 * 股数）+ 净有息负债 = 股价 * 股本数 + 短期借款 +长期借款 + 应付债券）内。

请问，现在的新的神奇公式是怎样运算的？
```

蕙蕙的basic excel表格如下：
![basic](https://cloud.githubusercontent.com/assets/19412465/24092955/763849bc-0d8c-11e7-8cdc-3c39b3a2e681.png)

**Comment by leilayanhui** [comment]
**胭脂王回复**

EBIT（息前税前利润）=净利润＋所得税费用＋分配股利、利润或偿付利息支付的现金（这里用财务费用代替）

净有形资产+净流动资产=所有者权益-商誉-股本

EV = 总市值（股价 * 股数）+ 净有息负债

**Comment by zhangshiyinrunwithcc** [comment]
好的 谢谢蕙蕙和胭脂王解答！
