### ISSUE TITLE
一阶工作安排

### ISSUE THREAD

**Issue by leilayanhui** [leilayanhui/Magic-Formula-Cn#3]
# 一阶工作安排
许从用任我们的产品经理~

开发文档简单点，感觉要花很多精力

### 进度表

日期|工作内容
---|---
2.22-2.24|爬取原始数据，建立原始数据表
2.22-2.24|制作登陆页面
2.27-3.2|计算神奇公司，生成荐股票列表
2.27-3.3|制作说明、荐股页面

## 后端
数据库四张表，还是用 SQLite 吧

1. custom
  - 用户名, cus_id
  - 密码, password
  - 邮箱, email
  - 荐股历史, history

2. original data
  - 证券代码,code
  - 证券名,name
  - 行业, industry
  - 上市日期, timeToMarket
  - 净利润, net_profits
  - 所得税费用
  - 分配股利
  - 利润
  - 偿付利息支付的现金
  - 货币资金
  - 交易性金融资产
  - 固定资产净额
  - 前一日收盘价（日期）
  - 股本数, totals
  - 短期借款
  - 长期借款
  - 应付债券

3. magic data
  - EBIT
  - EV
  - 分母（净有形资产+净流动资产）
  - EBIT/（净有形资产+净流动资产）（投资回报率）
  - EBIT/EV（收益率）
  - 投资回报率排名
  - 收益率排名
  - 神奇公式排名

4. Output
  - 证券代码,code
  - 证券名,name
  - 行业, industry
  - 上市日期, timeToMarket
  - 投资回报率结果
  - 回报率排名
  - ebit/ev结果
  - 收益率排名
  - 神奇公式结果
  - 神奇公式排名

## 前端
**登陆页面**

**说明页面**

**交互页面**：先30个，方便的话则全部股票

**交互页面样板**

证券号|证券名|行业|上市日期|好公司|好价格|神奇公式排名
---|---|---|---|---|---|---
000858|五粮液|饮料制造|1998-04-27|33.9(45)|9(10)|55(12)

**交互页面功能设想**

小金额的投资者，比如投资金额<30万，推荐20元以下的股票，剔除重复的行业。这样是否就要在用户表单中增加一列投资金额？

百万级，恢复正常，在前100的排名中随机荐股。

千万级，是否给点激进的组合，比如把ROTC换成利润增速

需要修改的，跟帖说明，我来改

**Comment by zhangshiyinrunwithcc** [comment]
### 神奇公式产品需求
- 获取季报年报数据
- 通过神奇公式选取30支股票
- 放入股票池
- 前端展示给用户
- 用户进行选股

### 2月22日-2月24日 未完成技术点
- @fatfox 提出 需要搭建**网站架构**
- @许从用 提出 需要**抓取数据**和**建立原始数据库**

### 2月22日-2月24日 已完成技术点
- @胭脂王 提供**神奇公式概念介绍** https://h5.ichangtou.com/minicfm/index.html?fmid=20170222
- @许从用 提出**API采集接口问题：多久爬去一次数据**
- @leilayanhui  确定**需要采集原始品种**并提供**原始数据API链接地址**
原始数据品种 http://tushare.org/fundamental.html
原始数据接口包 http://tushare.org/
- @leilayanhui  制作**前端登录界面V1.0** 如下图
![v1 0](https://cloud.githubusercontent.com/assets/19412465/23290331/fc5fb81e-fa8a-11e6-9f79-2fa46bca5f53.png)

### 技术求助
- @leilayanhui  请求@胭脂王**帮忙把我们需要的原始数据和api上的配下对**；
- @许从用 请求@all**有没有人帮忙看下数据上的哪些字段这些名字和这个网站的名字有些看不懂呢**
