### ISSUE TITLE
如何获取原始数据

### ISSUE THREAD

**Issue by leilayanhui** [leilayanhui/Magic-Formula-Cn#4]
# 原始数据表
### 基本面数据，[股票列表](http://tushare.org/fundamental.html#id2)
  code,代码
  name,名称
  industry,所属行业
  pe,市盈率
  totals,总股本(亿)
  fixedAssets,固定资产

### [业绩报告](http://tushare.org/fundamental.html#id3)
  net_profits,净利润(万元)

### [历史行情](http://tushare.org/trading.html#id2)
  close,收盘价

根据刘和宇给的公式，上述数据不够，需要通联的数据

### [合并资产负债表(Point in time)](https://mall.datayes.com/datapreview/151?lang=zh)
  货币资金货币资金, cashCEquiv
  交易性金融资产，tradingFA
  固定资产,  fixedAssets
  短期借款, STBorr
  长期借款, LTBorr
  应付债券, bondPayable

### [合并利润表(Point in time)](https://mall.datayes.com/datapreview/161?lang=zh)
  净利润, NIncome
  所得税, incomeTax

点击免费试用，试用30天

[通联文档中心](https://api.wmcloud.com/docs/pages/viewpage.action?pageId=2392676)

[数据试用说明](https://mall.datayes.com/tryDesc?lang=zh)

## 问题
1. @胭脂王 我记得听你说 tushare 的数据够用，那我上面列在通联里的数据要到哪找？

2.  固定资产净额、分配股利、利润或偿付利息支付的现金，这几个数据在哪里

**Comment by xucongyong** [comment]
我先写上面的，
下面的确定了就抓。

**Comment by yanzhiw** [comment]
@vanxv 
可以使用以下方法注册通联获取数据
[注册方法](http://tushare.org/datayes.html)
