### ISSUE TITLE
项目申请，注意里面的计划和分工

### ISSUE THREAD

**Issue by leilayanhui** [leilayanhui/Magic-Formula-Cn#5]
- 项目名称：神奇公式筛股器
- 团队项目协作仓库地址 ：[Magic Formula Cn](https://github.com/leilayanhui/Magic-Formula-Cn)
- 项目概述
	- 项目简介

    借鉴格林布拉特的神奇公式，带入中国公司的财报数据，计算出每支的投资回报率和收益率两项排名，然后将两个排名相加，获得一个的综合排名，排名越靠前的股票，其投资回报率和收益率的组合越佳。列出综合排名前30的股票，反馈给用户。

	- 你的项目重点解决用户什么问题？

    在短时间内为用户提供低价优质的股票

	- 目标用户是怎样的？

    有一定基础的长期投资者

	- 项目执行方案
	  - MVP 的核心功能是哪些？

        **前端**：注册页面、登陆页面、说明页面、交互页面（排名前30的股票列表）

        **后端**：三张数据表，一是原始数据表，二是神奇公式数据表，三是用户数据表

	  - 这三周开发的功能排期是怎样的？
        
        8w  爬取原始数据，注册页面

        9w  关联原始数据，登陆页面
        
        10w 输出最终排名，制作交互页面，美化页面
        
        11w 部署公网，制作 kenote
    
- 团队成员介绍
	- 分工
          - 产品经理： @vanxv 许从用
          - 原始数据表： @vanxv 许从用
          - 神奇公式数据表： @fatfox2016, @yanzhiw 刘和宇
          - 数据核实： @yanzhiw 刘和宇
          - 前端： @leilayanhui 严蕙, @zhangshiyinrunwithcc 张诗颖, @Yifan127 张一帆
          - 部署公网： @Yifan127 张一帆

	- 在微信群中的昵称：
           - 安徽阜阳-OS X-武黎-fatfox2016
           - 成都江浙沪广东 - 许从用
           - 上海-win-胭脂王-yanzhiw
           - 上海-win-严蕙-leilayanhui
           - 北京-OS X-张诗颖-zhangshiyinrun
           - 上海 - win10 - Yifan - Yifan127

有要修改的@我。还有给我你们的群昵称，我加进去

**Comment by zhangshiyinrunwithcc** [comment]
统一计划书。没有意见。辛苦了！

我的群昵称：张诗颖。

一个小修改：在团队成员介绍里面，似乎应该是`前端`而不是`前段`。

**Comment by yanzhiw** [comment]
同意计划书。另外我做一个原始数据表的需求吧~~包括用户如何使用等。

我的群昵称：胭脂王
