### ISSUE TITLE
【前端】神奇公式介绍

### ISSUE THREAD

**Issue by zhangshiyinrunwithcc** [leilayanhui/Magic-Formula-Cn#9]
### 神奇公式原理

神奇公式的本质是，`组合投资`。它的原理是，选取较多支不同类别股票，对冲风险获取最大收益。它的特点有两个，第一是`多样性组合`股票选取；第二是`长期持有`（至少持有12个月）。神奇公式相比较于传统选股，最为突出优点是`较高的收益率`和`稳定的收益率`。

### 神奇公式使用方法

- 第一步 ：使用神奇公式扫描器(Stock Screener)从数据库选择获取表现较优的股票列表(30-50个)；

- 第二步 ：从股票列表中，遵从多样化、大公司原则，选取股票(30个左右)

- 第三步 ：最后筛选一次，保留20支以上股票；

- 第四步 ：买入，并持有12个月以上。

出处：《神奇公司》官方网站https://www.magicformulainvesting.com/Home/HowItWorks

**Comment by zhangshiyinrunwithcc** [comment]
### 神奇公式官方主页

![screen shot 2017-03-06 at 09 55 29](https://cloud.githubusercontent.com/assets/19412465/23594198/172a8c9e-0253-11e7-902a-6bc7bc8ff63b.png)

### 神奇公式官方使用指南

![screen shot 2017-03-06 at 09 55 19](https://cloud.githubusercontent.com/assets/19412465/23594201/2053099a-0253-11e7-9559-d450e47e243b.png)

**Comment by leilayanhui** [comment]
### 使用方法
我根据原书写的，你看看：

1. 注册，登入后进入荐股页面。

2. 荐股页面会显示综合排名前 30 的股票。该排名是根据最近一期报表计算的综合排名。（例如，现在是 2017.3.6，最近一期报表是 2016 年的 3 季度报表）

3. 在30支股票中挑选你中意的股票。建议购买公司规模较大的股票，如 **市值** （需要问下胭脂王）以上，并且避开重复的行业。

4. 用你全部投资金额的 20%~33%，购买入排名靠前的 5~7 支股票。若你资金充裕也可一次买入全部 30 支股票。

5. 每个三个月重复第 4 步，直到投入你所有的投资资金。

6. 第一批买入的股票持有期满一年后，将其卖出。然后回到第 3 步，再次买入神奇公式推荐的股票。

7. 将此过程坚持至少 3~5 年。

**问题**：@zhangshiyinrunwithcc 你的神奇公式原理是根据神奇公式的网站来的吗？因为和我看的书里说的有些不同

**Comment by zhangshiyinrunwithcc** [comment]
恩，我感觉你的更加符合我们项目实际操作。

我去修改help.html文档。

**Comment by zhangshiyinrunwithcc** [comment]
### 神奇公式原理

神奇公式的本质是，`组合投资`。它的原理是，选取较多支不同类别股票，对冲风险获取最大收益。它的特点有两个，第一是`多样性组合`股票选取；第二是`长期持有`（至少持有12个月）。神奇公式相比较于传统选股，最为突出优点是`较高的收益率`和`稳定的收益率`。

### 神奇公式使用方法

- Step1 ：登录荐股页面,查看综合排名前 30 的股票。（该排名是根据深沪A股最近一期报表计算的综合排名：例如，现在是 2017.3.6，最近一期报表是 2016 年的 3 季度报表）

- Step2 ：用你全部投资金额的 20% ~ 33%，购买入排名靠前的 5~7 支股票，建议避免行业重复。若你资金充裕也可一次买入全部 30 支股票

- Step3 ：每个三个月重复第 4 步，直到投入你所有的投资资金

- Step4 ：第一批买入的股票持有期满一年后，将其卖出。然后回到第 3 步，再次买入神奇公式推荐的股票。将此过程坚持至少 3~5 年。

### 注意！

历史已证明神奇公式非常有效，但不能保证将来永远有效。股市有风险，投资需谨慎。

出处：《神奇公司》官方网站https://www.magicformulainvesting.com/Home/HowItWorks
